---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---

Bagging regression models for astronaut mission duration 

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r}
library(tidyverse)
library(tidymodels)
```

```{r}
astronauts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv")
```


```{r}
astronauts %>% 
  mutate(year_of_mission = factor(10* year_of_mission %/% 10)) %>% 
  ggplot(aes(year_of_mission, hours_mission)) +
  geom_boxplot(alpha = 0.2) +
  scale_y_log10() +
  labs(y = 'mission duration (h)', x = '')
```

## Select data

Pick predictors and log-transform mission duration.
```{r}
astronauts_df <- astronauts %>% 
  select(name, mission_title, hours_mission, year_of_mission,
         occupation, in_orbit) %>% 
  mutate(
    occupation = str_to_lower(occupation),
    in_orbit = case_when(
      str_detect(in_orbit, '^Salyut') ~ 'Salyut',
      str_detect(in_orbit, '^STS') ~ 'STS',
      TRUE ~ in_orbit
    )
    ) %>% 
  filter(hours_mission > 0) %>% 
  mutate(hours_mission = log(hours_mission))
```

## Split dataset

```{r}
set.seed(123)
astro_split <- initial_split(astronauts_df, strata = hours_mission)
astro_train <- training(astro_split)
astro_test <- testing(astro_split)
```


## Recipe

```{r}
astro_recipe <- recipe(hours_mission ~ ., data = astro_train) %>% 
  update_role(name, mission_title, new_role = 'id') %>% 
  step_other(occupation, in_orbit, threshold =0.05) %>% 
  step_dummy(all_nominal_predictors()) 

astro_recipe %>% prep() %>% juice()
```

## Build bootstrap aggregation (bagging) models

```{r}
library(baguette)

astro_wf <- workflow() %>% 
  add_recipe(astro_recipe)

tree_spec <- bag_tree() %>% 
  set_engine('rpart', times = 25) %>% 
  set_mode('regression')
  
mars_spec <- bag_mars() %>% 
  set_engine('earth', times = 25) %>% 
  set_mode('regression')

tree_res <- astro_wf %>% 
  add_model(tree_spec) %>% 
  fit(astro_train)

mars_res <- astro_wf %>% 
  add_model(mars_spec) %>% 
  fit(astro_train)
```

## Predict test data

```{r}
test_res <- astro_test %>% 
  bind_cols(predict(tree_res, astro_test)) %>% 
  rename(.pred_tree = .pred) %>% 
  bind_cols(predict(mars_res, astro_test)) %>% 
  rename(.pred_mars = .pred)
```


```{r}
test_res %>% metrics(hours_mission, .pred_tree)
```


```{r}
test_res %>% metrics(hours_mission, .pred_mars)
```


```{r}
new_astronauts <- 
  crossing(
    name = 'id', mission_title = 'id',
    in_orbit = c('ISS', 'STS', 'Mir', 'other'),
    military_civilian = 'civilian',
    occupation = 'other',
    year_of_mission = seq(1960, 2020, 10)
  ) %>% 
  filter(
    !(in_orbit == "ISS" & year_of_mission < 2000),
    !(in_orbit == "Mir" & year_of_mission < 1990),
    !(in_orbit == "STS" & year_of_mission < 1980),
    !(in_orbit == "STS" & year_of_mission > 2010)
  )
  
new_astronauts %>% 
  bind_cols(predict(mars_res, new_astronauts)) %>% 
  rename(mars = .pred) %>% 
  bind_cols(predict(tree_res, new_astronauts)) %>% 
  rename(tree = .pred) %>% 
  pivot_longer(c(mars,tree), names_to = 'model', values_to = 'pred') %>% 
  ggplot(aes(year_of_mission, 10**(pred), color = in_orbit)) +
  geom_line() +
  geom_point() +
  scale_y_log10() +
  facet_wrap(~model)+
  labs(y = 'Mission duration (h), predicted', color = 'orbiter')
```

